# Generated by Django 4.0.3 on 2022-05-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlunoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlunoEmail', models.CharField(max_length=50)),
                ('AlunoSenha', models.CharField(max_length=50)),
            ],
        ),
    ]
