# Generated by Django 4.0.3 on 2022-05-12 18:32

import WebAppEAD.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('absenceId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('studentId', models.IntegerField()),
                ('count', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('date', models.DateField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('identifier', models.IntegerField()),
                ('studentId', models.IntegerField()),
                ('title', models.CharField(max_length=1500)),
                ('classId', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('createdBy', models.IntegerField()),
                ('updatedBy', models.IntegerField()),
                ('deliveredAt', models.DateTimeField()),
                ('deliveredMaterial', models.CharField(max_length=1500)),
                ('score', models.FloatField()),
                ('attachment', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroomId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('createdBy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('eventType', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('teacherName', models.CharField(max_length=1500)),
                ('title', models.CharField(max_length=1500)),
                ('description', models.CharField(max_length=1500)),
                ('dateOfEvent', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('updatedBy', models.IntegerField()),
                ('status', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('MaterialId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1500)),
                ('description', models.CharField(max_length=1500)),
                ('attachment', models.CharField(max_length=1500)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('createdBy', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('teatcherId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachingPlan',
            fields=[
                ('teachingPlanId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1500)),
                ('description', models.CharField(max_length=1500)),
                ('teacherName', models.CharField(max_length=1500)),
                ('State', models.IntegerField()),
                ('workload', models.IntegerField()),
                ('absencesLimit', models.IntegerField()),
                ('year', models.DateField()),
                ('evaluation', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=1500)),
                ('email', models.CharField(max_length=1500)),
                ('password', models.CharField(max_length=1500)),
                ('phone', models.CharField(max_length=1500)),
                ('birthdate', models.DateTimeField()),
                ('profileType', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('events', djongo.models.fields.ArrayField(model_container=WebAppEAD.models.Event)),
                ('absences', djongo.models.fields.ArrayField(model_container=WebAppEAD.models.Absence)),
                ('assignments', djongo.models.fields.EmbeddedField(model_container=WebAppEAD.models.Assignment)),
                ('classrooms', djongo.models.fields.EmbeddedField(model_container=WebAppEAD.models.Classroom)),
            ],
        ),
    ]
