# Generated by Django 4.0.3 on 2022-05-26 19:35

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppEAD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='MaterialId',
            new_name='materialId',
        ),
        migrations.RenameField(
            model_name='teachingplan',
            old_name='State',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='absences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='classrooms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('eventId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('eventType', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('teacherName', models.CharField(max_length=1500)),
                ('title', models.CharField(max_length=1500)),
                ('description', models.CharField(max_length=1500)),
                ('dateOfEvent', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('updatedBy', models.IntegerField()),
                ('status', models.CharField(max_length=1500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAppEAD.user')),
            ],
        ),
    ]
