# Generated by Django 4.0.3 on 2022-05-30 18:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppEAD', '0003_userassignment_userabsence'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClassroom',
            fields=[
                ('classroomId', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('createdBy', models.IntegerField()),
                ('user', models.ManyToManyField(to='WebAppEAD.user')),
            ],
        ),
    ]
