# Generated by Django 4.0.3 on 2022-05-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppEAD', '0004_userclassroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='materialId',
            new_name='MaterialId',
        ),
    ]
