# Generated by Django 4.0.3 on 2022-05-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppEAD', '0005_rename_materialid_material_materialid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='teatcherId',
            new_name='teacherId',
        ),
    ]
