# Generated by Django 4.0.3 on 2022-05-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppEAD', '0006_rename_teatcherid_material_teacherid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassignment',
            name='studentId',
        ),
    ]
